name: Build and Push slo container image
on:
  push:
    branches:
      - main
    paths:
      - 'slo/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shawnlabo/demo-slo:latest
            ghcr.io/shawnlabo/demo-slo:${{ github.sha }}
